### ISSUE TITLE
incorrect key name in interval_block method

### ISSUE THREAD

**Issue by eignerchris** [VerdigrisTech/green-button-data#2]
The `interval_block` method contains a reference to `meter_Reading_id` - note the capital R.

https://github.com/VerdigrisTech/green-button-data/blob/cf86c573276ea21a560dff89dfec1ce2730f3eb8/lib/green-button-data/client.rb#L52

Because this key is wrong, it makes it difficult to use the `interval_block` method correctly.

**Comment by AndrewJo** [comment]
Thanks @eignerchris! Will fix and release a patch soon.

**Comment by AndrewJo** [comment]
Fixed. Released 0.4.2 which addresses this bug.
