### ISSUE TITLE
The problem about BulkSCERetailCustomer XML schema

### ISSUE THREAD

**Issue by peter279k** [VerdigrisTech/green-button-data#23]
As title, I also look at this [BulkSCERetailCustomer.xml](https://github.com/VerdigrisTech/green-button-data/blob/master/spec/fixtures/BulkSCERetailCustomer.xml), and it can help me to generate my electric customer data with Green Button Data standard.

I also look at following XML tree snippets:

```XML
<entry>
    <id>48A0CAE0-4426-11E6-A457-5463F7008592</id>
    <link rel="self" href="https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource/RetailCustomer/VJEWP31BE/Customer/1/CustomerAccount/1111111/CustomerAgreement/NB6WRU/ServiceSupplier/msp" />
    <link rel="up" href="https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource/RetailCustomer/VJEWP31BE/Customer/1/CustomerAccount/1111111/CustomerAgreement/NB6WRU/ServiceSupplier" />
    <link rel="related" href="https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource/RetailCustomer/VJEWP31BE/Customer/1/CustomerAccount/1111111/CustomerAgreement/NB6WRU/ServiceSupplier/msp/EndDevice" />
    <title />
    <content>
      <ServiceSupplier xmlns="http://naesb.org/espi/customer">
        <kind>msp</kind>
        <issuerIdentificationNumber>SCE</issuerIdentificationNumber>
      </ServiceSupplier>
    </content>
    <updated>2016-07-07T02:36:29</updated>
    <published>2016-07-07T02:36:29</published>
  </entry>
```

It has the `<link rel="related" href="https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource/RetailCustomer/VJEWP31BE/Customer/1/CustomerAccount/1111111/CustomerAgreement/NB6WRU/ServiceSupplier/msp/EndDevice" />` , but I don't find any `EndDevice` entry on this sample XML file.

I think some entries have this related link for `EndDevice` entry.

If I don't misunderstand this link tag with related attribute, this `EndDevice` is mapped to one specific entry that have related `EndDevice` link.

Can anyone explain why `EndDevice` entry doesn't need to be existed on this file?

**Comment by tedWexus** [comment]
It's most likely that the this sample XML file is not up-to-date. The example was created almost 4 years ago and the only changes made since then were the ones I made in November to reflect some namespace changes I observed. There are probably new elements that SCE has added in the past four years that could be added.

**Comment by peter279k** [comment]
Hi @tedWexus, thanks for your reply.

I see. This customer data XML is not latest version of Green Button Data standard.

I also know that the electric data XML with Green Button Data standard has the [DMD validation tool](http://dmdvalidator.greenbuttonalliance.org/#testresults) and it can use this to validate XML has the correct Green Button Data standard.

But the retail customer data doesn't have the similar validation tool can validate XML schema.

That's why I refer this file you create to try to generate my customer data XML.

Or do you have the way to validate these customer XML with Green Button Data standard?

Thanks :).

**Comment by tedWexus** [comment]
> Or do you have the way to validate these customer XML with Green Button Data standard?

@peter279k Currently, I do not. I have not had to update my usage of the Green Button data from SCE, so I am probably missing out on some data. It would be nice if the example was up-to-date.

**Comment by peter279k** [comment]
@tedWexus, thanks for your reply.

Here are some XML schema files can help you to update these sample XML files.

[espi.xsd](https://naesb.org//copyright/espi.xsd)
[retailcustomer.xsd](https://naesb.org//copyright/customer.xsd)

**Comment by AndrewJo** [comment]
@peter279k @tedWexus please feel free to submit a PR with updated XML files. Closing stale issue.
